name: Nix Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .#hamcp-server

  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --no-build
